# Generated by Django 3.2.6 on 2022-01-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_product'),
        ('diller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('diller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diller.diller')),
            ],
        ),
        migrations.CreateModel(
            name='Busket_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('busket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diller.busket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.product')),
            ],
        ),
    ]
