# Generated by Django 4.0.1 on 2022-01-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diller',
            name='language',
            field=models.IntegerField(choices=[(0, 'uz'), (1, 'ru')]),
        ),
    ]
