# Generated by Django 4.0.1 on 2022-01-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0002_alter_diller_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diller',
            name='language',
            field=models.IntegerField(choices=[(0, 'uz'), (1, 'ru')], null=True),
        ),
    ]
