# Generated by Django 3.2.6 on 2022-01-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0003_auto_20220127_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busket_item',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='busket_item',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='busket_item',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='busket_item',
            name='is_purchased',
        ),
        migrations.AddField(
            model_name='busket_item',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
