# Generated by Django 3.2.6 on 2022-01-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0005_auto_20220127_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='diller',
            name='status',
            field=models.IntegerField(choices=[(0, 'Kutilmoqda'), (1, 'Qabul qilingan'), (2, 'Rad etilgan')], default=0),
        ),
    ]
