# Generated by Django 3.2.6 on 2022-01-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0006_diller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='busket',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busket',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
