# Generated by Django 4.0.1 on 2022-01-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0007_auto_20220127_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='busket',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Naqd'), (1, 'Nasiya')], default=0),
            preserve_default=False,
        ),
    ]
