# Generated by Django 4.0.1 on 2022-01-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0009_alter_busket_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diller',
            name='ball',
            field=models.IntegerField(default=2),
        ),
    ]
