# Generated by Django 4.0.1 on 2022-02-05 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_dillergifts_sellergifts'),
        ('diller', '0013_busket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergiftdiller',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.dillergifts'),
        ),
    ]
