# Generated by Django 4.0.1 on 2022-02-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_gifts'),
        ('diller', '0014_alter_ordergiftdiller_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busket_item',
            name='busket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diller.busket'),
        ),
        migrations.AlterField(
            model_name='busket_item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.product'),
        ),
        migrations.AlterField(
            model_name='diller',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.district'),
        ),
        migrations.AlterField(
            model_name='diller',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.regions'),
        ),
        migrations.AlterField(
            model_name='ordergiftdiller',
            name='gift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.gifts'),
        ),
        migrations.AlterField(
            model_name='ordergiftdiller',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diller.diller'),
        ),
    ]
