# Generated by Django 4.0.1 on 2022-02-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0015_alter_busket_item_busket_alter_busket_item_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busket',
            name='active',
        ),
    ]
