# Generated by Django 4.0.1 on 2022-02-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0017_busket_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busket',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diller',
            name='balls',
            field=models.IntegerField(default=0),
        ),
    ]
