# Generated by Django 4.0.1 on 2022-02-10 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0018_alter_busket_ordered_date_alter_diller_balls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busket',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
