# Generated by Django 4.0.1 on 2022-02-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0020_alter_busket_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftdiller',
            name='status',
            field=models.IntegerField(choices=[(0, 'Kutilmoqda'), (1, 'Qabul qilingan'), (3, 'Rad etilgan')], default=0),
        ),
    ]
