# Generated by Django 4.0.1 on 2022-10-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0023_alter_diller_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diller',
            name='language',
            field=models.IntegerField(choices=[(0, 'uz'), (1, 'ru')], default=0),
        ),
    ]
