# Generated by Django 4.0.1 on 2022-02-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='balls',
            field=models.IntegerField(default=0),
        ),
    ]
