# Generated by Django 4.0.1 on 2022-02-05 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_dillergifts_sellergifts'),
        ('seller', '0004_cvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergiftseller',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.sellergifts'),
        ),
    ]
