# Generated by Django 4.0.1 on 2022-02-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_gifts'),
        ('seller', '0005_alter_ordergiftseller_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvitation',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.seller'),
        ),
        migrations.AlterField(
            model_name='ordergiftseller',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.gifts'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.district'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.regions'),
        ),
    ]
