# Generated by Django 4.0.1 on 2022-02-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_cvitation_seller_alter_ordergiftseller_gift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftseller',
            name='status',
            field=models.IntegerField(choices=[(0, 'Kutilmoqda'), (1, 'Qabul qilingan'), (3, 'Rad etilgan')], default=0),
        ),
    ]
