# Generated by Django 4.0.1 on 2022-02-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_cvitation_seller_alter_ordergiftseller_gift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photo'),
        ),
        migrations.AddField(
            model_name='seller',
            name='shop_location',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='seller',
            name='shop_passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_passport_photo'),
        ),
    ]
