# Generated by Django 4.0.1 on 2022-02-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_seller_passport_photo_seller_shop_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='shop_location',
            field=models.JSONField(default=dict),
        ),
    ]
