# Generated by Django 4.0.1 on 2022-02-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_ordergiftseller_status'),
        ('seller', '0008_alter_seller_shop_location'),
    ]

    operations = [
    ]
