# Generated by Django 4.0.1 on 2022-02-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_merge_20220223_1725'),
        ('seller', '0009_merge_20220226_1137'),
    ]

    operations = [
    ]
