# Generated by Django 3.2.13 on 2022-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_merge_20220226_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Kutilmoqda'), (1, 'Qabul qilingan'), (3, 'Rad etilgan')], default=0),
        ),
    ]
