# Generated by Django 4.0.1 on 2022-10-01 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_cvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvitation',
            name='current_ball',
            field=models.IntegerField(default=0),
        ),
    ]
