# Generated by Django 4.0.1 on 2022-10-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_cvitation_created_at_cvitation_current_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.IntegerField(choices=[(0, 'Kutilmoqda'), (1, 'Qabul qilingan'), (2, 'Rad etilgan')], default=0),
        ),
    ]
