# Generated by Django 4.0.1 on 2022-10-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0022_alter_busket_payment_type_alter_busket_status'),
        ('seller', '0013_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='dillers',
            field=models.ManyToManyField(to='diller.Diller'),
        ),
    ]
