# Generated by Django 4.0.1 on 2022-10-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_alter_seller_dillers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.IntegerField(choices=[(0, 'Kutilmoqda'), (1, 'Qabul qilingan'), (2, 'Rad etilgan'), (3, 'Muzlatilgan')], default=0),
        ),
    ]
