# Generated by Django 4.0.1 on 2023-01-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_alter_product_price'),
        ('seller', '0018_alter_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.product'),
        ),
    ]
