done = "✅"
prev = "⏮"
next = "⏭"
comment = "💬"
cross = "❌"
trash = "🗑"
reload = "🔄"

LANGUAGE, NAME, NUMBER, REGION, DISTRICT, MENU, SELECT_CATEGORY, SELECT_PRODUCT, SELECT_PRODUCT_COUNT, CART, PURCHASED, PAYMENT_TYPE, BALL, PROMOTION_COUNT, SELECT_NEW_LANGUAGE = range(15)

TOKEN = "5271053431:AAF54PTgM_3B01wTPDj-WiXy3nkOx03JWXM"

