done = "✅"
prev = "⏮"
next = "⏭"
comment = "💬"
cross = "❌"
trash = "🗑"
reload = "🔄"

LANGUAGE, NAME, NUMBER, REGION, DISTRICT, MENU, SELECT_CATEGORY, SELECT_PRODUCT, SELECT_PRODUCT_COUNT, CART, PURCHASED, PAYMENT_TYPE, BALL, PROMOTION_COUNT, SELECT_NEW_LANGUAGE = range(15)

TOKEN = "5637769125:AAEpF_YprHMUMHxPKdUEVXIk_7SMd1dcSfQ"
# TOKEN = "2112456432:AAEUUvXeAwZPSLq6dCSv_yZoODt134wY_dg"

