<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-01-26 06:56

from django.db import migrations, models
=======
# Generated by Django 3.2.6 on 2022-01-26 10:20

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> f01f3646362570eef19134c230ffeeae9106f3ef


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_data', models.TextField()),
                ('ru_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
>>>>>>> f01f3646362570eef19134c230ffeeae9106f3ef
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uz_data', models.TextField()),
                ('ru_data', models.TextField()),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_data', models.TextField()),
                ('ru_data', models.TextField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.regions')),
            ],
        ),
>>>>>>> f01f3646362570eef19134c230ffeeae9106f3ef
    ]
