# Generated by Django 3.2.6 on 2022-01-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ball',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
