# Generated by Django 4.0.1 on 2022-01-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('diller', '0011_rename_ball_diller_balls'),
        ('admin_panel', '0007_baseproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='diller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diller.diller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='saler',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Saled'), (2, 'Returned')], default=0),
            preserve_default=False,
        ),
    ]
