# Generated by Django 4.0.1 on 2022-02-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_baseproduct_diller_baseproduct_saler_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderGift',
        ),
    ]
