# Generated by Django 4.0.1 on 2022-02-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Saled'), (2, 'Returned')], default=0),
        ),
    ]
