# Generated by Django 4.0.1 on 2022-02-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_baseproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
