# Generated by Django 4.0.1 on 2022-02-04 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0012_ordergiftdiller'),
        ('admin_panel', '0013_rename_description_promotion_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('bought_count', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diller.diller')),
            ],
        ),
    ]
