# Generated by Django 4.0.1 on 2022-02-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_remove_promotion_order_bought_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='saler',
        ),
    ]
