# Generated by Django 4.0.1 on 2022-02-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_remove_baseproduct_saler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='status',
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
