# Generated by Django 4.0.1 on 2022-02-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_rename_ball_gifts_diller_ball_gifts_seller_ball'),
    ]

    operations = [
        migrations.CreateModel(
            name='DillerGifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('ball', models.IntegerField()),
                ('image', models.ImageField(upload_to='gifts')),
            ],
        ),
        migrations.CreateModel(
            name='SellerGifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('ball', models.IntegerField()),
                ('image', models.ImageField(upload_to='gifts2')),
            ],
        ),
    ]
