# Generated by Django 4.0.1 on 2022-02-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_delete_gifts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ball',
            new_name='diller_ball',
        ),
        migrations.AddField(
            model_name='product',
            name='seller_ball',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
