# Generated by Django 4.0.1 on 2022-02-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_rename_ball_product_diller_ball_product_seller_ball'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_type', models.IntegerField(choices=[(0, 'Diller'), (1, 'Sotuvchi')])),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('ball', models.IntegerField()),
                ('image', models.ImageField(upload_to='gifts')),
            ],
        ),
    ]
