# Generated by Django 4.0.1 on 2022-02-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_cvitation_seller_alter_ordergiftseller_gift_and_more'),
        ('admin_panel', '0022_gifts'),
        ('diller', '0015_alter_busket_item_busket_alter_busket_item_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DillerGifts',
        ),
        migrations.DeleteModel(
            name='SellerGifts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='diller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diller.diller'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.product'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.product'),
        ),
    ]
