# Generated by Django 4.0.1 on 2022-02-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_delete_dillergifts_delete_sellergifts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='bought_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
