# Generated by Django 4.0.1 on 2022-02-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_promotion_bought_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='bought_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
