# Generated by Django 4.0.1 on 2022-02-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_product_diller_nasiya_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
