# Generated by Django 4.0.1 on 2022-03-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_alter_baseproduct_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='price',
            field=models.FloatField(),
        ),
    ]
