# Generated by Django 4.0.1 on 2022-10-02 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_alter_seller_dillers'),
        ('admin_panel', '0031_alter_product_price_alter_promotion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.seller'),
        ),
    ]
