# Generated by Django 4.0.1 on 2022-10-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_alter_product_code_delete_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_code',
            field=models.IntegerField(default=0),
        ),
    ]
