done = "✅"
prev = "⏮"
next = "⏭"
comment = "💬"
cross = "❌"
trash = "🗑"
reload = "🔄"


BACK = {
    "uz": "🔙 Ortga",
    "ru": "🔙 Назад"
}

LANGUAGE, NAME, NUMBER, REGION, ACCOUNT, HOLDER, MENU, CASHBACK, CVI_PHOTO, CVI_SERIAL_NUMBER, BALL,  SELECT_NEW_LANGUAGE, CARD, PASSPORT_PHOTO,CASHBACK_PHOTO,DILLERS_CHOICE  = range(
    16)


SALE_PROMOCODE = "SALE_PROMOCODE"
SALE_PROMOCODE_IMAGE = "SALE_PROMOCODE_IMAGE"
# TOKEN = "5414863758:AAGSQYe8fnYn7UCX0BcBdcpjiOlES5mnfYU"
# TOKEN = "6525921476:AAHn9ocU5-ik7TMuFScvpAw6BAlJwrpywkI"
TOKEN = "5160030689:AAGMXHsfA-Ex4vYBN7SvEki6c9Mg4Am1gmM"
