done = "✅"
prev = "⏮"
next = "⏭"
comment = "💬"
cross = "❌"
trash = "🗑"
reload = "🔄"

LANGUAGE, NAME, NUMBER, REGION, ACCOUNT, HOLDER, MENU, CASHBACK, CVI_PHOTO, CVI_SERIAL_NUMBER, BALL,  SELECT_NEW_LANGUAGE, CARD, PASSPORT_PHOTO,CASHBACK_PHOTO,DILLERS_CHOICE  = range(
    16)

TOKEN = "5414863758:AAGSQYe8fnYn7UCX0BcBdcpjiOlES5mnfYU"
