done = "✅"
prev = "⏮"
next = "⏭"
comment = "💬"
cross = "❌"
trash = "🗑"
reload = "🔄"

LANGUAGE, NAME, NUMBER, REGION, DISTRICT, SHOP, MENU, CVI, CVI_PHOTO, CVI_SERIAL_NUMBER, BALL, SELECT_NEW_LANGUAGE, SHOP_LOCATION, PASSPORT_PHOTO,SHOP_PASSPORT_PHOTO = range(
    15)

TOKEN = "5550475528:AAEF1MFvRA25V2B84wxRjA_vAeDaqWPPBws"
