done = "✅"
prev = "⏮"
next = "⏭"
comment = "💬"
cross = "❌"
trash = "🗑"
reload = "🔄"

LANGUAGE, NAME, NUMBER, REGION, DISTRICT, SHOP, MENU, CVI, CVI_PHOTO, CVI_SERIAL_NUMBER, BALL,  SELECT_NEW_LANGUAGE, SHOP_LOCATION, PASSPORT_PHOTO,SHOP_PASSPORT_PHOTO,DILLERS_CHOICE  = range(
    16)

# TOKEN = "5550475528:AAEF1MFvRA25V2B84wxRjA_vAeDaqWPPBws"
TOKEN = "5779631816:AAHHEiy-Y2fac1iQjGajf1FXaoElYAf-UPw"
