# Generated by Django 4.0.1 on 2023-08-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_saleseller_language_alter_saleseller_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleseller',
            name='state',
            field=models.SmallIntegerField(default=1),
        ),
    ]
