# Generated by Django 4.0.1 on 2023-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_saleseller_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleseller',
            name='account',
            field=models.BigIntegerField(default=0),
        ),
    ]
