# Generated by Django 4.0.1 on 2023-08-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_serialnumbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumbers',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serialnumbers',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.saleseller'),
        ),
    ]
