# Generated by Django 4.0.1 on 2023-08-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_serialnumbers_is_used_serialnumbers_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.card')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.saleseller')),
            ],
        ),
    ]
