# Generated by Django 4.0.1 on 2023-09-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_alter_saleseller_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumbers',
            name='used_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
