# Generated by Django 4.0.1 on 2024-03-27 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0024_alter_diller_language'),
        ('sale', '0011_serialnumbers_used_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='saleseller',
            name='diller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_sellers', to='diller.diller'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('seria', models.CharField(max_length=255)),
                ('letter', models.CharField(max_length=255)),
                ('code', models.IntegerField()),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.car')),
                ('diller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diller.diller')),
            ],
        ),
    ]
