# Generated by Django 4.0.1 on 2024-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_car_saleseller_diller_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='seria',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='promocode',
            unique_together={('car', 'seria', 'letter', 'code')},
        ),
    ]
