# Generated by Django 4.0.1 on 2024-03-29 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0014_alter_promocode_options_promocode_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='got_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
