# Generated by Django 4.0.1 on 2024-04-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0015_promocode_created_at_promocode_got_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to='sale.saleseller'),
        ),
        migrations.CreateModel(
            name='PromocodeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promo_request_images')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_requests', to='sale.promocode')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_requests', to='sale.saleseller')),
            ],
        ),
    ]
