# Generated by Django 4.0.1 on 2024-04-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0016_alter_promocode_seller_promocoderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocoderequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Kutilmoqda'), (2, 'Tasdiqlandi'), (3, 'Rad etildi')], default=1),
        ),
    ]
