# Generated by Django 4.0.1 on 2024-04-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_alter_product_price'),
        ('sale', '0017_alter_promocoderequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.district')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.regions')),
            ],
        ),
        migrations.AlterField(
            model_name='promocode',
            name='diller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to='sale.salediller'),
        ),
        migrations.AlterField(
            model_name='saleseller',
            name='diller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_sellers', to='sale.salediller'),
        ),
    ]
