# Generated by Django 4.0.1 on 2024-04-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0018_salediller_alter_promocode_diller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSeller2',
            fields=[
                ('saleseller_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.saleseller')),
            ],
            bases=('sale.saleseller',),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to='sale.saleseller2'),
        ),
        migrations.AlterField(
            model_name='promocoderequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_requests', to='sale.saleseller2'),
        ),
        migrations.AlterField(
            model_name='usergift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='sale.saleseller2'),
        ),
    ]
